This is my first Notebook in Kaggle, This code is inspired by the https://www.kaggle.com/sinakhorami/titanic-best-working-classifier notebook

## Import necessary libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

/home/mo/anaconda3/envs/ml35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/mo/anaconda3/envs/ml35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/mo/anaconda3/envs/ml35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


## Importing train data into pandas DataFrame

In [2]:
import os
# os.listdir('../')

train = pd.read_csv('./train.csv')

In [3]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

### Checking for data missing in the dataframe

In [4]:
df_info = train.describe()
print(train.shape)
df_info

(891, 12)


PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [5]:
train['Age'].fillna(train.Age.mean(), inplace=True)

In [6]:
# Filled Age missing values with the mean of Age
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  891.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   13.002015    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   22.000000    0.000000   
50%     446.000000    0.000000    3.000000   29.699118    0.000000   
75%     668.500000    1.000000    3.000000   35.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

### Removing the features which are not impacting more on the Survival decission

In [7]:
drop_features = ['Name', 'PassengerId', 'Ticket', 'Cabin']
train = train.drop(drop_features, axis = 1)

### Creating OneHotEncoder using pandas get_dummies - since machine learning handles only with numbers

In [8]:
train = pd.get_dummies(train)
# label encoder can also be used

In [9]:
train.describe()

Survived      Pclass         Age       SibSp       Parch        Fare  \
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000   
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208   
std      0.486592    0.836071   13.002015    1.102743    0.806057   49.693429   
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000   
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400   
50%      0.000000    3.000000   29.699118    0.000000    0.000000   14.454200   
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000   
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200   

       Sex_female    Sex_male  Embarked_C  Embarked_Q  Embarked_S  
count  891.000000  891.000000  891.000000  891.000000  891.000000  
mean     0.352413    0.647587    0.188552    0.086420    0.722783  
std      0.477990    0.477990    0.391372    0.281141    0.447876  
min      0.000000    0.000000    0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000    0.000000    0.000000  
50%      0.000000    1.000000    0.000000    0.000000    1.000000  
75%      1.000000    1.000000    0.000000    0.000000    1.000000  
max      1.000000    1.000000    1.000000    1.000000    1.000000

### Now we have Final train data is ready, Lets start train out models

In [10]:
train.head()

Survived  Pclass   Age  SibSp  Parch     Fare  Sex_female  Sex_male  \
0         0       3  22.0      1      0   7.2500           0         1   
1         1       1  38.0      1      0  71.2833           1         0   
2         1       3  26.0      0      0   7.9250           1         0   
3         1       1  35.0      1      0  53.1000           1         0   
4         0       3  35.0      0      0   8.0500           0         1   

   Embarked_C  Embarked_Q  Embarked_S  
0           0           0           1  
1           1           0           0  
2           0           0           1  
3           0           0           1  
4           0           0           1

## Lets use multiple algorithms for training and select the best out of it

In [11]:
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import accuracy_score, log_loss

/home/mo/anaconda3/envs/ml35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/mo/anaconda3/envs/ml35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


### Importing different Classifier Algorithams

In [12]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression

/home/mo/anaconda3/envs/ml35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/mo/anaconda3/envs/ml35/lib/python3.5/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [13]:
classifiers = [
    KNeighborsClassifier(3),
    SVC(probability=True),
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    AdaBoostClassifier(),
    GradientBoostingClassifier(),
    GaussianNB(),
    LinearDiscriminantAnalysis(),
    QuadraticDiscriminantAnalysis(),
    LogisticRegression()
]

In [14]:
log_cols = ['Classifier', 'Accuracy']
log = pd.DataFrame(columns=log_cols)

In [30]:
sss = StratifiedShuffleSplit(n_splits=10, test_size=0.2, random_state=0)

# X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])
# y = np.array([0, 0, 0, 1, 1, 1])
# print(type(y))
X = train.iloc[:, 1:].values
y = train.iloc[:, 0].values
# print(type(y))


print("X ", X.shape)
print("y ", y.shape)

# acc_dict = {}

for train_index, test_index in sss.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
#     pass
    


X  (891, 10)
y  (891,)


array([[ 3.        , 29.69911765,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 3.        , 29.69911765,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 3.        , 29.69911765,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [ 3.        , 39.        ,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 3.        , 29.69911765,  2.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 3.        , 22.        ,  0.        , ...,  0.        ,
         0.        ,  1.        ]])

array([[ 3.  ,  0.75,  2.  , ...,  1.  ,  0.  ,  0.  ],
       [ 2.  , 36.  ,  1.  , ...,  0.  ,  0.  ,  1.  ],
       [ 1.  , 49.  ,  1.  , ...,  1.  ,  0.  ,  0.  ],
       ...,
       [ 3.  , 17.  ,  1.  , ...,  1.  ,  0.  ,  0.  ],
       [ 1.  , 35.  ,  0.  , ...,  0.  ,  0.  ,  1.  ],
       [ 3.  , 30.5 ,  0.  , ...,  0.  ,  0.  ,  1.  ]])

array([[ 3.        , 29.69911765,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 1.        , 35.        ,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 1.        , 50.        ,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [ 3.        , 30.        ,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 3.        , 19.        ,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 2.        , 16.        ,  0.        , ...,  0.        ,
         0.        ,  1.        ]])

array([[ 2.        , 70.        ,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 3.        , 40.        ,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 1.        , 11.        ,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [ 2.        , 30.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 3.        , 29.69911765,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 3.        , 21.        ,  0.        , ...,  0.        ,
         0.        ,  1.        ]])

array([[ 3. , 39. ,  1. , ...,  0. ,  0. ,  1. ],
       [ 2. , 50. ,  0. , ...,  0. ,  0. ,  1. ],
       [ 2. , 32.5,  0. , ...,  0. ,  0. ,  1. ],
       ...,
       [ 3. ,  4. ,  4. , ...,  0. ,  0. ,  1. ],
       [ 3. , 30. ,  0. , ...,  1. ,  0. ,  0. ],
       [ 2. , 29. ,  1. , ...,  0. ,  0. ,  1. ]])

array([[ 1.        , 22.        ,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 3.        , 19.        ,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 3.        , 23.        ,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [ 2.        , 21.        ,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 1.        , 42.        ,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 3.        , 29.69911765,  0.        , ...,  0.        ,
         0.        ,  1.        ]])

array([[ 1.        , 52.        ,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 3.        , 29.69911765,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 1.        , 17.        ,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [ 2.        , 37.        ,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 3.        , 45.        ,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 1.        , 29.69911765,  0.        , ...,  1.        ,
         0.        ,  0.        ]])

array([[ 3.        , 29.69911765,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 3.        , 29.69911765,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 3.        , 18.        ,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [ 3.        , 40.        ,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 1.        , 27.        ,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 3.        , 22.        ,  0.        , ...,  0.        ,
         0.        ,  1.        ]])

array([[ 3. , 21. ,  0. , ...,  0. ,  0. ,  1. ],
       [ 3. , 14. ,  5. , ...,  0. ,  0. ,  1. ],
       [ 2. , 47. ,  0. , ...,  0. ,  0. ,  1. ],
       ...,
       [ 1. , 16. ,  0. , ...,  1. ,  0. ,  0. ],
       [ 3. , 14.5,  1. , ...,  1. ,  0. ,  0. ],
       [ 3. , 29. ,  1. , ...,  0. ,  0. ,  1. ]])

array([[ 3., 18.,  0., ...,  0.,  0.,  1.],
       [ 2., 33.,  1., ...,  0.,  0.,  1.],
       [ 3., 34.,  1., ...,  0.,  0.,  1.],
       ...,
       [ 3., 27.,  0., ...,  0.,  0.,  1.],
       [ 1., 35.,  1., ...,  0.,  0.,  1.],
       [ 3., 31.,  0., ...,  0.,  0.,  1.]])

In [85]:
s1 = 'Other – LOCK AT BOTTOM'
s2 = 'Can’t remember – LOCK AT BOTTOM/OCO . CAN’T BE CODED WITH ANYTHING ELSE .'
remove = ['LOCK AT BOTTOM/OCO . CAN’T BE CODED WITH ANYTHING ELSE .', 'LOCK AT BOTTOM']

In [86]:
# te = [s1.replace(x, '') for x in remove]

import re
for x in remove:
    if re.search(x, s2): 
        test = s1.replace(x, '')
        break
    print(test)